name: Build and Run React Frontend in Docker

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional, for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (optional, if pushing images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t react-app .

      # Step 5: Run the Docker container
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:80 react-app

      # Step 6: Test the running app (optional)
      - name: Test App
        run: |
          curl --fail http://localhost:3000 || exit 1
