name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package
      env:
        MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"

    - name: Debug - List project files
      run: ls -la

    - name: Build Docker image
      run: |
        docker build -t my-springboot-app .
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker tag my-springboot-app:latest swathiselvaraju/my-springboot-app:latest
        docker push swathiselvaraju/my-springboot-app:latest
      env:
        DOCKER_BUILDKIT: 1
