name: Build and Push springboot Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the Docker image


      - name: Build with Maven
        run: mvn clean package

     - name: Build Docker image for backend
       run: |
       docker build -t my-backend-app -f Dockerfile .
       echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
       docker tag my-backend-app:latest swathiselvaraju/my-backend-app:latest
       docker push swathiselvaraju/my-backend-app:latest
      env:
        DOCKER_BUILDKIT: 1
